=== mikos2004/ISEL_LEIM_2223_MoP/TP3/CódigoTP3/TP3/src/out/production/TP3/tp3/XML/BaseDados.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT BaseDados (Eventos,Patrocinadores)*>
        <!ELEMENT Eventos (Festival|Espetaculo)*>
        <!ELEMENT Festival (Nome,Eventos+)>
        <!ATTLIST Festival
                codFestival CDATA #IMPLIED>
        <!ELEMENT Nome (#PCDATA)>
        <!ELEMENT Espetaculo (Nome,Artistas+,Localidade)>
        <!ATTLIST Espetaculo
                codEspetaculo CDATA #IMPLIED
                numBilhetes CDATA #REQUIRED>
        <!ELEMENT Artistas (Artista)+>
        <!ELEMENT Artista (#PCDATA)>
        <!ELEMENT Localidade (#PCDATA)>
        <!ELEMENT Patrocinadores (Patrocinador)*>
        <!ELEMENT Patrocinador (Nome)+>
        <!ATTLIST Patrocinador
                codEvento CDATA #REQUIRED
                valor CDATA #REQUIRED>

=== mikos2004/ISEL_LEIM_2223_MoP/TP3/CódigoTP3/TP3/src/out/production/TP3/tp3/XML/BaseDados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BaseDados SYSTEM "BaseDados.dtd">
<BaseDados>
	<Eventos>
		<Festival>
			<Nome>Músicas do Mundo</Nome>
			<Eventos>
				<Espetaculo codEspetaculo = "E01" numBilhetes = "10000">
					<Nome>Abertura do Festival Músicas do Mundo</Nome>
					<Artistas>
						<Artista>Júlio Isidro</Artista>
						<Artista>Ana Moura</Artista>
					</Artistas>
					<Localidade>Sines</Localidade>
				</Espetaculo>
				<Festival>
					<Nome>Música Cubana</Nome>
					<Eventos>
						<Espetaculo numBilhetes = "500">
							<Nome>Pablo Milanés</Nome>
							<Artistas>
							<Artista>Pablo Milanés</Artista>
							</Artistas>
							<Localidade>Sines</Localidade>
						</Espetaculo>
						<Espetaculo numBilhetes = "400">
							<Nome>Compay Segundo</Nome>
							<Artistas>
								<Artista>Compay Segundo</Artista>
							</Artistas>
							<Localidade>Sines</Localidade>
						</Espetaculo>
						<Espetaculo numBilhetes = "400">
							<Nome>Silvio Rodríguez</Nome>
							<Artistas>
								<Artista>Silvio Rodríguez</Artista>
							</Artistas>
							<Localidade>Sines</Localidade>
						</Espetaculo>
					</Eventos>
				</Festival>
				<Festival codFestival="F01">
					<Nome>African Music Awards</Nome>
					<Eventos>
						<Espetaculo numBilhetes = "200">
							<Nome>Miriam Makeba</Nome>
							<Artistas>
								<Artista>Miriam Makeba</Artista>
							</Artistas>
							<Localidade>Porto Côvo</Localidade>
						</Espetaculo>
						<Espetaculo numBilhetes = "400">
							<Nome>Bonga</Nome>
							<Artistas>
								<Artista>Bonga</Artista>
							</Artistas>
							<Localidade>Sines</Localidade>
						</Espetaculo>
						<Espetaculo numBilhetes = "400">
							<Nome>Yuri da Cunha</Nome>
							<Artistas>
								<Artista>Yuri da Cunha</Artista>
							</Artistas>
							<Localidade>Sines</Localidade>
						</Espetaculo>
					</Eventos>
				</Festival>
			</Eventos>
		</Festival>
	</Eventos>
	<Patrocinadores>
		<Patrocinador codEvento="E01" valor="1000000"><Nome>EDP</Nome></Patrocinador>
		<Patrocinador codEvento="E01" valor="10000"><Nome>Pingo Doce</Nome></Patrocinador>
		<Patrocinador codEvento="E01" valor="50000"><Nome>Vodafone</Nome></Patrocinador>
		<Patrocinador codEvento="F01" valor="40000"><Nome>Vodafone</Nome></Patrocinador>
	</Patrocinadores>
</BaseDados>
